### PR TITLE
Fix permissions and add DNAME variable

### LINKED ISSUE #59: Add default CN in env for management portal JKS
The install script has become interactive, querying for the CN properties of the ManagementPortal certificate. Instead, the CN should be configurable through the `.env` file.

### PR DESCRIPTION
**Pull request by blootsvoets**
More strict permissions on data on the server. Right now any user with server access can read the radar configuration. This should be limited to superusers and the owner. Fixes #59.

### CODE REVIEW

File: dcompose-stack/radar-cp-hadoop-stack/install-radar-stack.sh [hunk 1]
```diff
@@ -1,6 +1,11 @@
 #!/bin/bash
 
 . ./util.sh
+
+sudo-linux chmod og-rw ./.env
+sudo-linux chmod og-rwx ./etc
+sudo-linux chmod og-rwx ./output
```
Comment (yatharthranjan) [inline dcompose-stack/radar-cp-hadoop-stack/install-radar-stack.sh]: Should check if the directory exists first

File: dcompose-stack/radar-cp-hadoop-stack/etc/env.template [hunk 2]
```diff
@@ -1,4 +1,5 @@
 SERVER_NAME=localhost
+MANAGEMENTPORTAL_KEY_DNAME=CN=localhost, OU=MyName, O=MyOrg, L=MyCity, S=MyState, C=MyCountry
```
Comment (yatharthranjan) [inline dcompose-stack/radar-cp-hadoop-stack/etc/env.template]: Please remove the space after the commas
